name: Deploy to Server

on:
  push:
    branches: [ main ]  # Запускать при пуше в main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10  # Популярное действие для SSH
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e  # Остановить выполнение при любой ошибке

            echo "Пользователь: $(whoami)"
            cd /home/deploy/telegrambot

            echo "Загрузка последних изменений..."
            git pull telegrambot main

            echo "Проверка изменения окружения..."
            if git diff --name-only HEAD@{1} HEAD | grep -q requirements.txt; then
              echo "Установка нового окружения..."
              source venv/bin/activate
              pip install -r requirements.txt
              deactivate
            else
              echo "Окружение не изменялось."
            fi

            echo "Перезапуск сервиса..."
            sudo systemctl restart servicebot.service

            echo "Автодеплой выполнен!"

            echo "Проверка успешного запуска сервиса..."
            sudo systemctl is-active --quiet servicebot.service
